FROM python:3.10-slim

# Install Ghostscript
RUN apt-get update && apt-get install -y ghostscript

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Install Python dependencies
RUN pip install -r requirements.txt

# Run the app
CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:10000"]



